### PR TITLE
lock timechart behind feature

### PR DESCRIPTION
**Pull request by bananaturtlesandwich**
just a pr for #2 which puts the timechart and timedata behind the timechart feature - more features can always be made for other charts in the future
also made the feature rely on the `instant` crate which works on wasm and actually doesn't add bloat on native because it falls back to the standard library

### CODE REVIEW

**Comment by bananaturtlesandwich** [comment]
might make a PR in future to let the examples compile to wasm so there can be web demos

**Comment by Gip-Gip** [comment]
Will get to it tonight, thanks again!

**Comment by Gip-Gip** [comment]
Just added a user notice to remind them to enable the feature, and also enabled the feature so that it is tested with cargo check/test. Documentation will also now be automatically generated for the feature when the crate is published.

**Comment by bananaturtlesandwich** [comment]
Great!

**Pull request merged**
