### PR TITLE
make chart data generic and mutable

### PR DESCRIPTION
**Pull request by bananaturtlesandwich**
- chart data is now generic instead of using the awkward `std::any::Any`
- data must be specified on instantiation and remain the same type throughout (don't see much use case for changing type)
- if you don't want to have any data use () as shown in the 3d chart example
- data can be mutated via `set_data` which takes a callback similar to egui's `ui.input()`
- cleaned up some code with clippy suggestions
- examples and docs have been updated :)
- thank you for the wonderful crate!

### CODE REVIEW

**Comment by Gip-Gip** [comment]
Sorry for not noticing this earlier, not sure why I didn't just do this. I'll take a look at it after I get some coffee. Changes made in the new version should be easy to implement.

**Comment by Gip-Gip** [comment]
I made the following minor changes:
 * Changed `.data` to `.get_data` so it doesn't conflict with the current function naming scheme, where a function without a prefix like `get_` or `set_` is often a setter that consumes itself.
 * Added a return type to `.set_data` to allow more flexability and be more similar to the egui data set methods.
 * Changed the callback to an FnOnce since it will only be called once.
 * Fixed examples in `lib.rs` and `README.md`
I really appreciate the time you took to contribute! Anything else you can suggest? Any changes you don't like?

**Comment by Gip-Gip** [comment]
Also just adapted the code to 0.3.0, went pretty smoothly

**Comment by bananaturtlesandwich** [comment]
Just realised there probably isn't much point to use a callback for `set_data` - might as well just give a mutable reference but apart from that I really appreciate the merge ❤

**Comment by bananaturtlesandwich** [comment]
Oh wait there's also another thing I guess probably restrict builtin chart types to a feature since a lot of the time people won't use them - also std::time::Instant doesn't compile on wasm afaik

**Comment by Gip-Gip** [comment]
* I'll decide on what is most efficient with the `.set_data` funciton. Callback provides a nice isolated scope for you to modify the data but it's kinda unusual and perhaps overly complicated.
 * Eh, perhaps, I think they're useful if I'm honest but on the following point it probably wouldn't be a bad idea.
 * I don't really use wasm at all so I completely overlooked no_std. Not sure how well it works I should probably make an example.
 * Arcs are just faster to clone and work with, so long as the data doesn't need to mutate. Video explaining why [here](https://www.youtube.com/watch?v=A4cKi7PTJSs).

**Comment by Gip-Gip** [comment]
I'll decide everything tomorrow I need to wake up in 8 hours and go to work though so not the best time to fix this lol

**Comment by bananaturtlesandwich** [comment]
Gotcha thx for answering

**Comment by Gip-Gip** [comment]
>     * you should probably put the builtin chart types behind a feature since most people won't use them
> 
>     * std::time::Instant doesn't exist on wasm so the timechart stuff won't work there (the above would avoid this problem but wouldn't allow any future builtins or you could put the type in the example or you could use the instant crate but you don't really want another dependency so I think probably just put in the example)

I'm not quite sure how I'm going to get it working with wasm yet, apparently plotter supports it but it also requires backends to implement the Error trait, which is in the standard library only. I'll have to look at it when I have more time; I'm currently on lunch break, I'm a little confused.

**Comment by bananaturtlesandwich** [comment]
Wasm isn't no std it just doesn't have the time and fs modules due to platform agnostics

**Comment by bananaturtlesandwich** [comment]
Also you uncapitalised some of the code in the readme :p

**Comment by Gip-Gip** [comment]
> Also you uncapitalised some of the code in the readme :p

I know there is a typo in the commit but it is fixed. Melatonin kicking in and I wanted to knock this out of the way lol

It's kinda embarrassing how many times I try to yank a block in vim and accidentally hit 'u'. And even more embarrassing in that I don't even notice it most of the time until I get compile errors.

I'll work on making charts a separate feature in another branch, I think this code achieves the goal it was set for though and I'll go ahead and merge it. Thanks again!

**Comment by bananaturtlesandwich** [comment]
Thanks!

**Pull request merged**
